/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Conexion.modConexionDB;
import Logica.Cont_OB_v2;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumnos
 */
public class FBuscarComuna extends javax.swing.JFrame {

    /**
     * Creates new form FBuscarCargo
     */
//    static String IDC,NC;
    //static String ncol;
    static int select;
    public FBuscarComuna() {
        initComponents();
        modConexionDB.conexionDB();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_BuscarCCR = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCCR = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_numreg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_regsel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Comuna");

        txt_BuscarCCR.setText("*");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TablaCCR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Comuna", "Nombre Comuna", "ID Ciudad", "Nombre Ciudad", "ID Region", "Nombre Region"
            }
        ));
        TablaCCR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCCRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCCR);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por Comuna, Ciudad, o Region:");

        jLabel5.setText("Numero de Registros:");

        txt_numreg.setText("--");

        jLabel7.setText("Registro Seleccionado:");

        txt_regsel.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_numreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_regsel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_BuscarCCR, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BuscarCCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_numreg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_regsel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Metodo del Boton Buscar*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        DefaultTableModel tablatem = (DefaultTableModel) TablaCCR.getModel();
        Cont_OB_v2 BCCR = new Cont_OB_v2();
        ResultSet RS;
        
        if (txt_BuscarCCR.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Advertencia", null, WIDTH);
        }else{
        txt_regsel.setText("--");
        tablatem.setRowCount(0);
        TablaCCR.setModel(tablatem);
        try {
            if (txt_BuscarCCR.getText().equals("*")){
            RS = BCCR.Listar_CCR();
            }else{
            RS = BCCR.Buscar_CCR(txt_BuscarCCR.getText());
         }
          Object [] fila;
            int contador = 0;
             while(RS.next()){ 
                 fila = new Object[7];/*Es para setearlo, reasignar nuevamente memoria*/
                     fila[0] = RS.getString("id_comuna");
                     fila[1] = RS.getString("nombre_comuna");
                     fila[2] = RS.getString("id_ciudad");
                     fila[3] = RS.getString("nombre_ciudad");
                     fila[4] = RS.getString("id_region");
                     fila[5] = RS.getString("nombre_region");
                 tablatem.addRow(fila);
             }
             TablaCCR.setModel(tablatem);
             txt_numreg.setText(Integer.toString(TablaCCR.getRowCount()));             
        } catch (SQLException ex) {
            Logger.getLogger(FMenuCargo.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TablaCCRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCCRMouseClicked
        txt_regsel.setText(Integer.toString(TablaCCR.getSelectedRow()+1));
        //select = (TablaCargos.getSelectedRow()+1);
    }//GEN-LAST:event_TablaCCRMouseClicked

    /*Metodo del Boton Aceptar*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        DefaultTableModel tablatem = (DefaultTableModel) TablaCCR.getModel();
        //FMenuInsertModEmpleado.IDC = TablaCargos.getColumnName(ncol);
     
        
        /*Analizar el tema del 0 en el getValueAt, porque no funciona cuando selecciono una columna mas alla del 0*/
       
        FMenuNuevoEmpleado.IDCOM = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()).toString();
        FMenuNuevoEmpleado.txt_IDComuna.setText(FMenuNuevoEmpleado.IDCOM);
        
        FMenuNuevoEmpleado.NCOM = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()+1).toString();
        FMenuNuevoEmpleado.txt_NComuna.setText(FMenuNuevoEmpleado.NCOM);
        
        FMenuNuevoEmpleado.IDCIUD = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()+2).toString();
        FMenuNuevoEmpleado.txt_IDCiudad.setText(FMenuNuevoEmpleado.IDCIUD);
        
        FMenuNuevoEmpleado.NCIUD = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()+3).toString();
        FMenuNuevoEmpleado.txt_NCiudad.setText(FMenuNuevoEmpleado.NCIUD);
        
        FMenuNuevoEmpleado.IDREG = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()+4).toString();
        FMenuNuevoEmpleado.txt_IDRegion.setText(FMenuNuevoEmpleado.IDREG);
        
        FMenuNuevoEmpleado.NREG = TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()+5).toString();
        FMenuNuevoEmpleado.txt_NRegion.setText(FMenuNuevoEmpleado.NREG);
        
//        FMenuInsertModEmpleado.IDC =    TablaCCR.getValueAt(0, TablaCCR.getSelectedRow()).toString();         
//        FMenuInsertModEmpleado.txt_IDCargo.setText(FMenuInsertModEmpleado.IDC);
//        
//        
//        FMenuInsertModEmpleado.NC = TablaCCR.getValueAt(0, TablaCCR.getSelectedColumn()).toString();        
//        FMenuInsertModEmpleado.txt_NCargo.setText(FMenuInsertModEmpleado.NC);
        
        
        System.out.println(FMenuNuevoEmpleado.IDCOM);
        System.out.println(FMenuNuevoEmpleado.NCOM);
        System.out.println(FMenuNuevoEmpleado.IDCIUD);
        System.out.println(FMenuNuevoEmpleado.NCIUD);
        System.out.println(FMenuNuevoEmpleado.IDREG);
        System.out.println(FMenuNuevoEmpleado.NREG);
        
        //System.out.println(FMenuInsertModEmpleado.NC);
        dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBuscarComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBuscarComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBuscarComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBuscarComuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBuscarComuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCCR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_BuscarCCR;
    private javax.swing.JLabel txt_numreg;
    private javax.swing.JLabel txt_regsel;
    // End of variables declaration//GEN-END:variables
}
